# Logo
logo_image_source: http://i.imgur.com/LpkkK5m.png

# Index Page
index_banner_text: Solitary Pursuits
index_banner_text_secondary: Rantings of a solitary pursuit in the Tech world
index_font_awesome_icon_css: fa fa-fort-awesome

# Header
menu:
  Home: /
  Archives: /archives
#  About: /about.html
#  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa fa-code

# Archive Date Format
archive_date_format: YYYY MMMM
archive_font_awesome_icon_css: fa fa-archive

# About Widget
about_widget_avatar_url: http://i.imgur.com/OXCWwy7.jpg
about_widget_text: "My name is Kumar Anirudha and this is my blog.<br>Tech evangelist.<br> I currently reside in Bangalore."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: anistark

# Google Analytics Tracking ID
google_analytics: UA-66400830-1

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/kranirudha
    fa_icon: fa fa-twitter
  - url: https://www.facebook.com/kranirudha
    fa_icon: fa fa-facebook
#  - url: https://dribbble.com/
#    fa_icon: fa-dribbble
  - url: https://github.com/anistark
    fa_icon: fa fa-github
#  - url: https://plus.google.com/
#    fa_icon: fa fa-google-plus
#  - url: https://www.behance.net/
#    fa_icon: fa fa-behance
#  - url: https://500px.com/
#    fa_icon: fa fa-500px
  - url: mailto:mail@anirudha.org
    fa_icon: fa fa-envelope
  - url: /atom.xml
    fa_icon: fa fa-rss

# Footer about
footer_about: "<a class=\"link dim white\" href=\"http://www.anirudha.org/\">Kumar Anirudha</a>"

# Home Page Date Format
home_date_format: MMMM Do YYYY


